### ISSUE TITLE
I am confused which package to use?

### ISSUE THREAD

**Issue by AkshayGadekar** [AnourValar/eloquent-serialize#12]
I making package to export unlimited bulky data into CSV, I need to send eloquent query into queue jobs, so its necessary for me to serialize eloquent query, and then unserialize back. User may send any type of query, long, short, with lots of relationships, etc. So I just wanted to ask if this package is capable of handling all types of queries. 
I found other packages doing such things too:
https://github.com/laravie/serialize-queries
https://github.com/laravel/serializable-closure 

Please do help me, before I publish the package.

**Comment by AnourValar** [comment]
Hello!

This package is fine for your goal, as well as two others. It's just depends on your preferences.

**Comment by AkshayGadekar** [comment]
OK, AnourValar I will use this package, I appreciate your efforts.
Thank you so much.
For any queries or share some doubts, is there any way to contact you?

**Comment by AnourValar** [comment]
I'm always in touch on Github :)

**Comment by AkshayGadekar** [comment]
hi @AnourValar , does this serialize all eloquent we use for mysql, mongoDB (Jenssegers\Mongodb\Eloquent\Model), pgsql, sqlite, etc...

**Comment by AnourValar** [comment]
It should work with every DB engines that Eloquent supports by default

**Comment by AkshayGadekar** [comment]
hi, I forgot to to tell you I have made a package:
https://github.com/AkshayGadekar/bulkExportCSV
Without "eloquent-serialize", I could have never able to make this package, so thanks.
Please go through my package, give me feedback and give star to the repo.
