### ISSUE TITLE
Error Invalid parameter number when use with() with where()

### ISSUE THREAD

**Issue by mcolominas** [AnourValar/eloquent-serialize#17]
If you use a `with()` without any `where()` it works fine, but when using the `where()`, it gives the error `SQLSTATE[HY093]: Invalid parameter number`.

Edit:
What I explained above works well, but it gives the error, when in the relationship it has a `where()` and when doing the `with()` it has another `where()` with the same value.

Example:
```php
//Model
public function translation()
{
    return $this->hasOne(ProductTranslation::class)->where('locale', 'en');
}
```
```php
use AnourValar\EloquentSerialize\Facades\EloquentSerializeFacade;

$query = Product::with(['translation' => function ($query) {
    $query->where('locale', 'en');
}]);
$serializedQuery = EloquentSerializeFacade::serialize($query);
$newQuery = EloquentSerializeFacade::unserialize($serializedQuery);
$newQuery->get()
```

**Comment by AnourValar** [comment]
I can't to reproduce the bug. Are you using the latest version of this package (1.2.22) ?
