### ISSUE TITLE
Serialization Exception occurs when serializing a nested having query

### ISSUE THREAD

**Issue by zpwparsons** [AnourValar/eloquent-serialize#19]
A `Serialization of 'Closure' is not allowed` exception occurs when serializing a query with nested `having` clauses.

Simplest example:
```php
$query = User::having(fn (Builder $query) => $query->having('email', 'example@example.com'));

EloquentSerialize::serialize($query);
```

**Comment by AnourValar** [comment]
Hello. Thanks for you feedback.

Fixed in [v1.2.25](https://github.com/AnourValar/eloquent-serialize/releases/tag/1.2.25)
