### ISSUE TITLE
Duplication of Eager Loaded Relation's Additional Criteria

### ISSUE THREAD

**Issue by andrewskm** [AnourValar/eloquent-serialize#4]
Running the serialize/unserialize on a Builder instance where `with()` is being called with a relation that has `orderBy()` or any other eloquent criteria added in the relation definition causes duplication of that addition to it's query.
It runs ok with where clauses, but errors on orderby since duplicates are not allowed.

*Relationship*
```php
public function userRoles(): BelongsToMany
{
    return $this->belongsToMany(UserRole::class)->orderBy('name');
}
```
**or**
```php
public function userRoles(): BelongsToMany
{
    return $this->belongsToMany(UserRole::class)->whereNotNull('name');
}
```

*Eloquent*
```php
$entries = Privilege::with(['userRoles']);
$queryBuilder = \EloquentSerialize::serialize($entries);
$testEntries = \EloquentSerialize::unserialize($queryBuilder);
ddd($testEntries->get());
```

*Sql Error When Using orderBy()*
`A column has been specified more than once in the order by list. Columns in the order by list must be unique`.

This does work when removed from the relation and added into the with as a closure, but then we lose the global default.

**Comment by AnourValar** [comment]
One more time thank you to give a feedback :)
New release with a fix have been published.

**Comment by andrewskm** [comment]
Works perfectly now, and again, thank you for the quick release!
