### ISSUE TITLE
You don't need this anymore

### ISSUE THREAD

**Issue by Stevemoretz** [AnourValar/eloquent-serialize#8]
Love what you done here but laravel forked a very popular package which already can do this, (actually this is just a small part of what it can do) and anyways it is now maintained by laravel itself :

https://github.com/laravel/serializable-closure

Give it a test if it works in all your tests, then your package isn't useful anymore.

**Comment by adiachenko** [comment]
@AnourValar It's only working because he skipped variable references. Not a very useful example. 

Passing either the builder or any complex types from parent scope will lead to unexpected behavior. More or less it just won't work. So for anyone wondering here accidentally you can just ignore this issue.

**Comment by Stevemoretz** [comment]
> @AnourValar It's only working because he skipped variable references. Passing either the builder or any complex type from parent scope will unravel this whole example. So for anyone wondering here accidentally you can just ignore this issue.

Your logic doesn't make sense, that example does everything this package can do (not more.) 
You can do more but as you see you gotta do some tricks sometimes, so don't pass any complex variable into the serialization, that's not the way serialization is intended to work, and that's also not what this package does either.

Serialization is usually used as a capsule and must not rely on complex external variables, unless you have to, and in those cases also you gotta be careful what you're doing, not everything can be serialized by default.

**Comment by Stevemoretz** [comment]
> @Stevemoretz Not at all.
> 
> When you serialize a builder directly, the caller can accept the builder from somewhere else and apply any other modifications based on some context object like request.
> 
> Your example, however, assumes that the builder will be created inside the closure which makes it unusable in a variety of scenarios. We're using a solution similar to this package internally because `laravel/serializable-closure` doesn't meet our needs.
> 
> `laravel/serializable-closure` is cool and all and offers secure signatures out of the box which makes it better for simpler uses, but if you need to serialize the query specifically, this package objectively supports more scenarios.

May I see your example, I'm interested in improving this if that's the case, I might find a solution for your use case.

**Comment by adiachenko** [comment]
It's essentially similar to the first example from @AnourValar:

```
$builder = User::limit(1);
$closure = fn () => $builder;
$string = serialize(new SerializableClosure($closure));
```

We need to accept the query from somewhere else, apply callback that modifies the query, then serialize it. Attempting to do so results in an error in our case because SerializableClosure attempts to serialize the caller object instead of the referenced query.

The exact exception looks something like this:

```
TypeError
Typed property CallerObject::$exampleProperty must be an instance of Closure or null, Laravel\SerializableClosure\Serializers\Native used
```

If we create the query inside the serialized callback or reference only simple types from parent context, surely the problem goes away. But we need something else.

**Comment by Stevemoretz** [comment]
> It's essentially similar to the first example from @AnourValar:
> 
> ```
> $builder = User::limit(1);
> $closure = fn () => $builder;
> $string = serialize(new SerializableClosure($closure));
> ```
> 
> We need to accept the query from somewhere else, apply callback that modifies the query, then serialize it. Attempting to do so results in an error in our case because SerializableClosure attempts to serialize the caller object instead of the referenced query.
> 
> The exact exception looks something like this:
> 
> ```
> TypeError
> Typed property CallerObject::$exampleProperty must be an instance of Closure or null, Laravel\SerializableClosure\Serializers\Native used
> ```
> 
> If we create the query inside the serialized callback or reference only simple types from parent context, surely the problem goes away. But we need something else.

Actually there is one way getting passed around it, I'll send it to you, wish you sent your own example though but it's fine.

**Comment by Stevemoretz** [comment]
Here you go, you can do whatever you want. ;)
Just needs a little imagination.

```php
    private function whereYouNeedToSend($closure){
        $string = serialize(new SerializableClosure($closure));
        $builder = unserialize($string)->getClosure()();
        $users = $builder["query"]($builder["class"]::query())->toArray();
        return $users;
    }

    public function testComplexBuilder(){
        UserTest::factory()->create();

        $closure = fn () => [
            "query" => fn ($query) => $query->limit(1)->get(),
            "class" => UserTest::class
        ];

        $users = $this->whereYouNeedToSend($closure);
        $this->assertCount(1,$users);
    }
```

```
Time: 00:00.781, Memory: 30.00 MB

OK (1 test, 1 assertion)

Process finished with exit code 0
```

**Comment by Stevemoretz** [comment]
Forgot about this also:

`When you serialize a builder directly, the caller can accept the builder from somewhere else and apply any other modifications based on some context object like request.`

request doesn't make sense to be serialized, think about what you are trying to achieve first, why would you do that? Is that absolutely necessary or you are just doing it, because you think it's easier or cooler. Why not just get `$all = request->all()` and now use `$all` in your closure?

When you get to complex subjects in programming you gotta think a little differently.

**Comment by adiachenko** [comment]
You're still trying to circumvent the premise of the caller (in your case, testComplexBuilder) accepting the builder as the argument or otherwise getting it from somewhere else.

But I am too tired to argue. I've said my piece. Let everyone decide for themselves what they want to do.

**Comment by Stevemoretz** [comment]
I mentioned from the beginning you can't do it straight and you need some tricks, that was the best you could come up with to get the same exact result you wanted with it and I gave it away for free, the thing I've thought on for hours.

This was NOT an argument, I was trying to help you but do as you wish.
